/**
 * geometric-people engine tests.
 *
 * The physics is exact, so the tests are too: on data generated by a cube
 * law the best-fit constant reproduces it with zero error and the exponent
 * scan recovers 3. The RMSE is a genuine minimum at the generating
 * exponent, and a wrong exponent fits worse. Parsing is checked on the
 * Howell CSV shape.
 */
import { describe, expect, it } from 'vitest'
import {
  bestExponent,
  fitConstant,
  linearRmse,
  parseHeightWeight,
  predictWeight,
  scaleOf,
} from './engine'
import type { HW } from './engine'

// synthetic people whose weight is exactly 0.9 · height³ (relative units)
const heights = Array.from({ length: 40 }, (_, i) => 60 + i * 3) // 60–177 cm
const K = 2.1e-5
const cubes: HW[] = heights.map((h) => ({ height: h, weight: K * h ** 3 }))

describe('parseHeightWeight', () => {
  it('reads height and weight from the quoted-header CSV', () => {
    const rows = parseHeightWeight(`"height";"weight";"age";"male"
151.765;47.8256065;63;1
139.7;36.4858065;63;0`)
    expect(rows).toHaveLength(2)
    expect(rows[0]).toMatchObject({ height: 151.765, weight: 47.8256065 })
  })
})

describe('fitConstant', () => {
  it('reproduces a cube law with essentially zero error at b = 3', () => {
    const { rmse } = fitConstant(cubes, 3)
    expect(rmse).toBeLessThan(1e-6)
  })

  it('fits worse at the wrong exponent', () => {
    const good = fitConstant(cubes, 3).rmse
    const bad = fitConstant(cubes, 1).rmse
    expect(bad).toBeGreaterThan(good)
    expect(bad).toBeGreaterThan(1) // a line badly misses a cube across the range
  })
})

describe('bestExponent', () => {
  it('recovers the generating exponent 3', () => {
    const { b } = bestExponent(cubes, 1, 4, 300)
    expect(b).toBeCloseTo(3, 1)
  })

  it('the best power law is at least as good as a straight line', () => {
    const { rmse } = bestExponent(cubes)
    expect(rmse).toBeLessThanOrEqual(linearRmse(cubes) + 1e-9)
  })
})

describe('predictWeight', () => {
  it('is monotonic increasing in height for a positive exponent', () => {
    const scale = scaleOf(cubes)
    const { c } = fitConstant(cubes, 3, scale)
    const w1 = predictWeight(100, 3, c, scale)
    const w2 = predictWeight(150, 3, c, scale)
    expect(w2).toBeGreaterThan(w1)
  })

  it('matches the generating law on held-in heights', () => {
    const scale = scaleOf(cubes)
    const { c } = fitConstant(cubes, 3, scale)
    for (const h of [90, 120, 165]) {
      expect(predictWeight(h, 3, c, scale)).toBeCloseTo(K * h ** 3, 4)
    }
  })
})
